---

# Creates datatable: disease_name_table
table:

- disease: hepb
  disease_name: "Hepatitis B"
  
- disease: hib
  disease_name: "Haemophilus influenzae type b"
  
- disease: je
  disease_name: "Japanese encephalitis"

- disease: mena
  disease_name: "Meningitis A"
  
- disease: pcv
  disease_name: "Pneumococcal"
  
- disease: rota
  disease_name: "Rotavirus"
  
- disease: rubella
  disease_name: "Rubella"
  
- disease: yf
  disease_name: "Yellow fever"
  
- disease: measles
  disease_name: "Measles"
  
- disease: polio
  disease_name: "Poliomyelitis"
