---

# Creates datatable: vaccine_dict_table
table:

# - intervention: bcg
#   vaccine: 
#   - bcg
  
- intervention: bopv
  vaccine: 
  - opv
  
- intervention: bopv_ipv
  vaccine:
  - opv
  - ipv
  
- intervention: bopv_ipv_frac
  vaccine:
  - opv
  - ipv
  
# - intervention: diphcv4
#   vaccine: 
#   - dip_bx
  
# - intervention: diphteria
#   vaccine: 
#   - dip
  
# - intervention: dt
#   vaccine:
#   - dip
#   - tet
  
# - intervention: dt_tdt
#   vaccine:
#   - dip
#   - tet
  
# - intervention: dtap
#   vaccine:
#   - dip
#   - tet
#   - aper
  
- intervention: dtaphibhepbipv
  vaccine:
  # - dip
  # - tet
  # - aper
  - hib
  - hepb
  
# - intervention: dtp
#   vaccine:
#   - dip
#   - tet
#   - aper
  
# - intervention: dtpcv3
#   vaccine:
#   - dip
#   - tet
#   - aper
  
# - intervention: dtpcv4
#   vaccine:
#   - dip_bx
#   - tet_bx
#   - aper_bx
  
- intervention: dtphepb
  vaccine:
  # - dip
  # - tet
  # - aper
  - hepb
  
- intervention: dtphib
  vaccine:
  # - dip
  # - tet
  # - aper
  - hib
  
- intervention: dtphibhepb
  vaccine:
  # - dip
  # - tet
  # - aper
  - hib
  - hepb
  
- intervention: dtphibhepb3
  vaccine:
  # - dip
  # - tet
  # - aper
  - hib
  - hepb
  
- intervention: dtphibhepbipv
  vaccine:
  # - dip
  # - tet
  # - aper
  - hib
  - hepb
  
# - intervention: dtwp
#   vaccine:
#   - dip
#   - tet
#   - wper
  
- intervention: hepb
  vaccine: 
  - hepb
  
- intervention: hepb_bd
  vaccine: 
  - hepb_bd
  
- intervention: hepb_bdall
  vaccine: 
  - hepb_bd
  
- intervention: hepb3
  vaccine: 
  - hepb
  
- intervention: hib
  vaccine: 
  - hib
  
- intervention: hib3
  vaccine: 
  - hib
  
- intervention: hibhepb
  vaccine:
  - hib
  - hepb
  
- intervention: ipv
  vaccine: 
  - ipv
  
- intervention: japenc
  vaccine: 
  - je
  
- intervention: japenc_c
  vaccine: 
  - je
  
- intervention: m_mmr
  vaccine:
  - measles
  - rubella
  
- intervention: m_mr
  vaccine:
  - measles
  - rubella
  
- intervention: mcv1
  vaccine: 
  - mcv1
  
- intervention: mcv2
  vaccine: 
  - mcv2
  
- intervention: measles
  vaccine: 
  - measles
  
- intervention: men_a
  vaccine: 
  - mena
  
- intervention: men_a_conj
  vaccine:
  - mena
  
- intervention: men_ac
  vaccine: 
  - mena
  
- intervention: men_acw
  vaccine: 
  - mena
  
- intervention: men_acwy
  vaccine: 
  - mena
  
- intervention: men_acyw_135conj
  vaccine: 
  - mena
  
- intervention: men_acyw_conj
  vaccine: 
  - mena
  
- intervention: mmr
  vaccine:
  - measles
  - rubella
  
- intervention: mmr_polio
  vaccine:
  - measles
  - rubella
  - ipv
  
- intervention: mopv3
  vaccine: 
  - opv
  
- intervention: mr
  vaccine:
  - measles
  - rubella
  
- intervention: mr_mmr
  vaccine:
  - measles
  - rubella
  
- intervention: opv
  vaccine: 
  - opv
  
- intervention: opvt
  vaccine: 
  - opv
  
# - intervention: pab  # Protection at birth against neonatal tetanus
#   vaccine:
#   - tet_px
  
- intervention: pcv3
  vaccine: 
  - pcv
  
- intervention: pcv7
  vaccine: 
  - pcv
  
- intervention: pcv10
  vaccine: 
  - pcv
  
- intervention: pcv13
  vaccine: 
  - pcv
  
- intervention: penta_td
  vaccine:
  # - dip
  # - tet
  # - aper
  - hib
  - hepb
  
# - intervention: percv4
#   vaccine: 
#   - aper_bx
  
- intervention: pneumo_conj
  vaccine: 
  - pcv
  
- intervention: pol3
  vaccine:
  - opv
  - ipv
  
- intervention: ppv23
  vaccine: 
  - pcv
  
- intervention: rcv
  vaccine: 
  - rubella
  
- intervention: rotac
  vaccine: 
  - rota
  
- intervention: rotavirus
  vaccine: 
  - rota
  
# - intervention: td_s
#   vaccine:
#   - dip
#   - tet
  
# - intervention: tdap_s
#   vaccine:
#   - dip
#   - tet
#   - aper
  
- intervention: tdipv_s
  vaccine:
  # - dip
  # - tet
  - ipv
  
- intervention: tdpipv
  vaccine:
  # - dip
  # - tet
  # - aper
  - ipv
  
# - intervention: t
#   vaccine: 
#   - tet
  
# - intervention: tt2plus
#   vaccine: 
#   - tet
  
# - intervention: ttcv4
#   vaccine: 
#   - tet_bx
  
- intervention: yf
  vaccine: 
  - yf
  
- intervention: yfv
  vaccine: 
  - yf

# Vaccines not modelled
- intervention: "15hpv1_f"
- intervention: "15hpv1_m"
- intervention: "15hpvc_f"
- intervention: "15hpvc_m"
- intervention: all_vaccines
- intervention: bopv_mopv1
- intervention: bopv_mopv2
- intervention: dtpcv1
- intervention: dtpcv2
- intervention: dtphibhepb1
- intervention: dtphibhepb2
- intervention: diphcv5
- intervention: diphcv6
- intervention: flu_all
- intervention: flu_child1
- intervention: flu_child2
- intervention: flu_chronic_adult
- intervention: flu_chronic_all
- intervention: flu_chronic_ped
- intervention: flu_elderly
- intervention: flu_haj
- intervention: flu_hcw
- intervention: flu_other
- intervention: flu_pw
- intervention: flu_resident
- intervention: hepb1
- intervention: hepb2
- intervention: hpv_fem
- intervention: hpv_male
- intervention: ipv_frac
- intervention: ipv1
- intervention: ipv1_frac
- intervention: ipv2
- intervention: ipv2_frac
- intervention: japenc_1
- intervention: mcv
- intervention: men_b
- intervention: men_bc
- intervention: men_c_conj
- intervention: mopv1
- intervention: mopv2
- intervention: mumps
- intervention: pcv1
- intervention: pcv2
- intervention: percv_pw
- intervention: prhpv1_f
- intervention: prhpv1_m
- intervention: prhpvc_f
- intervention: prhpvc_m
- intervention: rcv1
- intervention: rota1
- intervention: rota2
- intervention: ttcv5
- intervention: ttcv6
- intervention: typhoid
- intervention: typhoid_conj
- intervention: vad1
