---

# Creates datatable: vaccine_name_table
table:

- vaccine: hepb
  vaccine_name: "Hepatitis B"
  
- vaccine: hepb_bd
  vaccine_name: "Hep B birth dose"
  
- vaccine: hib
  vaccine_name: "Haemophilus influenzae type b"
  
- vaccine: je
  vaccine_name: "Japanese encephalitis"
  
- vaccine: mena
  vaccine_name: "Meningitis A"
  
- vaccine: pcv
  vaccine_name: "Pneumococcal"
  
- vaccine: rota
  vaccine_name: "Rotavirus"
  
- vaccine: rubella
  vaccine_name: "Rubella"
  
- vaccine: yf
  vaccine_name: "Yellow fever"
  
- vaccine: mcv1
  vaccine_name: "Measles first dose"
  
- vaccine: mcv2
  vaccine_name: "Measles second dose"
  
- vaccine: measles
  vaccine_name: "Measles"
  
- vaccine: ipv
  vaccine_name: "Poliomyelitis inactivated"
  
- vaccine: opv
  vaccine_name: "Poliomyelitis oral"
