---

# Creates datatable: vaccine_age_table
table:

- vaccine: hepb
  age: 0
  
- vaccine: hepb_bd
  age: 0
  
- vaccine: hib
  age: 0
  
- vaccine: je
  age: 0
  
- vaccine: mena
  age: 0
  
- vaccine: pcv
  age: 0
  
- vaccine: rota
  age: 0
  
- vaccine: rubella
  age: 0
  
- vaccine: yf
  age: 0
  
- vaccine: mcv1
  age: 0
  
- vaccine: mcv2
  age: 4
  
- vaccine: measles
  age: 4
  
- vaccine: ipv
  age: 0
  
- vaccine: opv
  age: 0

# Source for DTP-containing booster dose age groups:
#   https://terrance.who.int/mediacentre/data/sage/SAGE_Docs_Ppt_Apr2017/10_session_diptheria/Apr2017_session10_diphtheria_vax_effectiveness.pdf
